- name: Ensure Redis is installed
  apt:
    name: redis-server
    state: present
    update_cache: true

- name: Start and enable Redis service
  systemd:
    name: redis-server
    state: started
    enabled: true

- name: Configure Redis settings
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf

- name: Ensure Redis is listening on the correct IP
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?bind'
    line: 'bind 0.0.0.0'

- name: Ensure Redis password is set (optional)
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?requirepass'
    line: 'requirepass yourpassword'

- name: Restart Redis to apply changes
  systemd:
    name: redis-server
    state: restarted
  when: ansible_facts.services['redis-server'].state != 'started'
