repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-json
