- name: download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer

- name: install composer
  shell: php /tmp/composer --install-dir=/usr/local/bin

- name: rename composer executable
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  become: true

- name: Set permissions for composer file
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  become: true
  notify: Restart Nginx

- name: "Install Composer dependencies"
  script: /usr/local/bin/composer install --no-scripts --no-dev

- name: "Cache the configuration"
  script: "php artisan config:cache"
  
- name: "Clear the view cache"
  script: "php artisan key:generate"

- name: "Clear the view cache"
  script: "php artisan db:seed"
  
- name: "Run the migrations"
  script: "php artisan migrate --force"