- name: download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer

- name: install composer
  shell: php /tmp/composer --install-dir=/usr/local/bin

- name: rename composer executable
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  become: true

- name: Set permissions for composer file
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  become: true
  notify: Restart Nginx

- name: unzip codebase
  shell: unzip /home/ubuntu/code.zip

- name: "Install Composer dependencies"
  shell: |
    cd /home/ubuntu/laravel-todolist-api/laravel-todolist-api && /usr/local/bin/composer install --no-scripts --no-dev
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: "Cache the configuration"
  shell: |
    cd /home/ubuntu/laravel-todolist-api/laravel-todolist-api && php artisan config:cache

- name: "Key generate"
  shell: |
    cd /home/ubuntu/laravel-todolist-api/laravel-todolist-api && php artisan key:generate

- name: "Run the migrations"
  shell: |
    cd /home/ubuntu/laravel-todolist-api/laravel-todolist-api && php artisan migrate --force

- name: "DB seeding"
  shell: |
    cd /home/ubuntu/laravel-todolist-api/laravel-todolist-api && php artisan db:seed
