- name: Update cache
  become: true
  apt:
    update_cache: true
    state: present

- name: Install packages essential for mariadb installation
  apt:
    name: 
      - software-properties-common
      - dirmngr
      - ca-certificates 
      - apt-transport-https

- name: Install MariaDB Server
  apt: 
    name: mariadb-server
    state: present
  
- name: Install MariaDB Client
  apt: 
    name: mariadb-client
    state: present

- name: Restart MariaDB 10.6
  service: 
    name: mysql 
    state: restarted

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Installing PyMySQL for creating databse
  pip:
    name: PyMySQL
    state: present

# - name: Include secrets
#   include_vars:
#     file: secrets.yml

- name: create user account for localhost
  community.mysql.mysql_user:
    name: "{{ mariadb_user_name }}"
    password: "{{ db_user_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    priv: '*.*:ALL'
    state: present

- name: Create new databases named laravel
  community.mysql.mysql_db:
    name: "{{ mariadb_db_name }}"
    login_user: "{{ mariadb_user_name }}"
    login_password: "{{ db_user_password }}"
    collation: "{{ collation }}"
    encoding: "{{ encoding }}"
    state: present
