- name: Installation install software-properties-common
  apt: 
    name: software-properties-common

- name: "Repo PHP"
  apt_repository:
    repo="ppa:ondrej/php"

- name: Install php
  apt:
    name: php{{ php_version }}-fpm
    state: present

- name: Install other packages
  apt:
    pkg:
      - libapache2-mod-fcgid
      - php8.3-fpm
      - php8.3-mysql
      - php8.3-bcmath
      - php8.3-mbstring
      - php8.3-xml
      - php8.3-cli
      - php8.3-curl
      - php8.3-gd
      - php8.3-zip
      - unzip
    state: present
    update_cache: true
