- name: Install Nginx
  apt:
    name:
      - nginx
    update_cache: true
    state: present

- name: delete the default config file for nginx
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Delete the matched files
  file:
    path: '/etc/nginx/sites-enabled/website-server-for-ami.conf'
    state: absent

- name: Install nginx configuration
  template:
    src: 'templates/nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{ server_name }}.conf'

- name: Enable the config template from Nginx available sites
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link
  notify: Restart Nginx

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted 