name: PROD SITE DEPLOYMENT
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zip -y

    - name: Running PHP linter
      continue-on-error: true
      uses: michaelw90/PHP-Lint@master

    - name: Create Environment
      run: |
        cat << EOF > .env
        APP_URL="https://localhost"
        APP_NAME=Laravel
        APP_ENV=local
        APP_KEY=ds23234
        APP_DEBUG=false
        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_DATABASE=${{ secrets.DB_NAME }}
        DB_USERNAME=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        BROADCAST_CONNECTION=log
        FILESYSTEM_DISK=local
        QUEUE_CONNECTION=database
        REDIS_CLIENT=phpredis
        REDIS_HOST=0.0.0.0
        REDIS_PASSWORD=null
        REDIS_PORT=6379
        EOF

    - name: Zip the code
      run: |
        zip -r code.zip .

    - name: Transfer the code
      run: |
        scp code.zip ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/app

    - name: Checkout the vault pass
      run: |
        cd ansible
        echo ${{ secrets.DB_PASSWORD }} > pass.yml

    - name: Run ansible playbook
      run: |
        cd ansible
        ansible-playbook configure.yml -i inventory.txt --vault-password-file pass.yml